#+STARTUP: showeverything
This file contains a list of open bugs that need work.

* The preview area should visually show how the hjkl keys move the blue box.
  
* rewrite ^ and $ to teleport the blue box. Currently, the blue box just
  slides accross the screen. If it hits something it stops there.
  
* make the score persistant after the user dies. Currently, when the user dies
  the score goes to 0.
  
** as the score increases, make the blocks fall faster. and possibly more block to fall.
   
* the blue box should be redrawn after the user dies.
  
* One cannot quit the game with w/ q
  
* When the game ends after the user has lost of of his lives,
  an error appears that says, error running timer, learn-evil-update-game void variable
  learn-evil-score-file whatever that means.
  
* As a vertical red log falls a user can get points by pressing x or X to delete it.
  
* Explain movements over time. Perhaps, pause the game, tell the user what to do, and
  temporarily suspend gravity, and let only the user's blue box move.
  
* When the program starts, display the options for the user:
  Would you like to learn:
  vim commands
  emacs commands
  god-mode commands
  dired commands
  etc.
  he or she can then decide what he or she wants to play.
  
* Here is an overview of how the game works:
  
1) reset everything (learn-evil-reset-game)
   
2) use learn-evil-mode-map
   
3) set the period (how quickly the blocks fall or the clock tick length)
   
4) every period of seconds, update the game (lean-evil-update-game)
   
   1) error checking
      
   2) erase all shapes (learn-evil-erase-shape)
      
   3) move all red logs down one
      
   4) hit == (learn-evil-test-shape)
      
   5) if hit then draw the shape, don't move it.
      
   6) if not hit then (learn-evil-shape-done)
      
      1) move the peice down
	 
      2) update the score
	 
      3) learn-evil-new-shape
