#+Author: Joshua Branson
#+Title: Arch GNU/Linux CheatSheet

* Change the virtual console keyboard layout
loadkeys dvorak
* Configuring Xorg Settings (keyboard layout)
You can tweak some of these settings w/ evtest tool
** change the X keyboard layout & swap caps
- do it through .xinitrc

  #+BEGIN_SRC sh :results raw
    cd ~/; cat .xinitrc | grep xkb;
  #+END_SRC

  #+RESULTS:
  setxkbmap dvorak
  setxkbmap -option 'ctrl:swapcaps'

** tweaking X11 settings
[[https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Frequently_used_options][Frequently Used Options]]

 #+BEGIN_SRC
 Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
    # You can enable or disable tap buttons
        Option "TapButton1" "1"
        Option "TapButton2" "2"
        Option "TapButton3" "3"

        # disable trackpad whilst typing
        PalmDetect=1
        # tweak the minimum amount of touch your palm has to touch to be considered a touch
        PalmMinWidth=8
        # tweak the minimum pressure to be considered a palm
        PalmMinZ=100
        # scrolling when you slide your finger down the edge of the track pad
        Option "VertEdgeScroll" "on"
        Option "VertTwoFingerScroll" "on"
        Option "HorizEdgeScroll" "on"
        Option "HorizTwoFingerScroll" "on"
        Option "CircularScrolling" "on"
        Option "CircScrollTrigger" "2"
        Option "EmulateTwoFingerMinZ" "40"
        Option "EmulateTwoFingerMinW" "8"
        Option "CoastingSpeed" "0"
        Option "FingerLow" "35"
        Option "FingerHigh" "40"
EndSection
 #+END_SRC
*** [[https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Disable_trackpad_while_typing][disable trackpad whilst typing]]

 #+BEGIN_SRC
 Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
    # You can enable or disable tap buttons
        Option "TapButton1" "1"
        Option "TapButton2" "2"
        Option "TapButton3" "3"

        # disable trackpad whilst typing
        PalmDetect=1
        # tweak the minimum amount of touch your palm has to touch to be considered a touch
        PalmMinWidth=8
        # tweak the minimum pressure to be considered a palm
        PalmMinZ=100

EndSection
 #+END_SRC
*** disable tapping buttons (lightly touching the mouse, NOT clicking it)

 #+BEGIN_SRC
 Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
    # You can enable or disable tap buttons
        Option "TapButton1" "1"
        Option "TapButton2" "2"
        Option "TapButton3" "3"

EndSection
 #+END_SRC
* Networking
** creating persistent internet device names
https://wiki.archlinux.org/index.php/Network_configuration#Change_device_name

When you first start your computer your internet device names will be odd like this:

#+BEGIN_SRC sh :results raw
ip link
#+END_SRC

#+RESULTS:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 60:33:4b:8e:60:d0 brd ff:ff:ff:ff:ff:ff
3: wlanp01: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 60:33:4b:09:d2:da brd ff:ff:ff:ff:ff:ff

To fix this, just create some default rules that use the devices MAC address to name it something readable.

#+BEGIN_SRC sh export:code
  cat /etc/udev/rules.d/10-network.rules;
#+END_SRC

#+BEGIN_SRC
# make my wifi be named wifi0
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="60:33:4b:09:d2:da", NAME="wifi0"
#make my ethernet be
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="60:33:4b:8e:60:d0", NAME="neteth0"
#+END_SRC
** creating netctl profiles
https://wiki.archlinux.org/index.php/Netctl#Configuration

Use some of the examples from

#+BEGIN_SRC sh
ls /etc/netctl/examples/
#+END_SRC

#+RESULTS:
| bonding                    |
| bridge                     |
| ethernet-custom            |
| ethernet-dhcp              |
| ethernet-static            |
| macvlan-dhcp               |
| macvlan-static             |
| mobile_ppp                 |
| openvswitch                |
| pppoe                      |
| tunnel                     |
| tuntap                     |
| vlan-dhcp                  |
| vlan-static                |
| wireless-open              |
| wireless-wep               |
| wireless-wpa               |
| wireless-wpa-config        |
| wireless-wpa-configsection |
| wireless-wpa-static        |


=cp /etc/netctl/examples/ethernet-dhcp /etc/netctl/ethernet-dhcp;=

 Then you just need to change the device name to your device.
** Controlling network traffick
*** nftables is the NEW way of implementing networking rules on your machine:
One can block all incoming traffic from Facebook, block specified ports, etc.
*** IPTables is the OLD way of implementing networking rules on your machine.
With it you can block all incoming data from facebook, a specified port, etc.
***
*** If you totally screw up your iptables, you can change them back to the default [[https://wiki.archlinux.org/index.php/Iptables#Resetting_rules][values]]:

#+BEGIN_SRC sh
su
  iptables -F
  iptables -X
  iptables -t nat -F
  iptables -t nat -X
  iptables -t mangle -F
  iptables -t mangle -X
  iptables -t raw -F
  iptables -t raw -X
  iptables -t security -F
  iptables -t security -X
  iptables -P INPUT ACCEPT
  iptables -P FORWARD ACCEPT
  iptables -P OUTPUT ACCEPT

#+END_SRC

#+RESULTS:
** Apache
** Mariadb
*** Unable to get the mariadb daemon to start
    #+BEGIN_SRC sh
      sudo systemctl start mysqld.service
    #+END_SRC

    # FIXME the command for this is on the arch wiki
    You might try a:

    #+BEGIN_SRC sh
      mysql_update_root -p
    #+END_SRC
** enabling and disabling network interfaces (turning on/off wifi and ethernet)

#+BEGIN_SRC sh :results raw
  ip addr show
#+END_SRC

#+RESULTS:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: neteth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 60:33:4b:8e:60:d0 brd ff:ff:ff:ff:ff:ff
    inet 172.16.112.114/22 brd 172.16.115.255 scope global neteth0
       valid_lft forever preferred_lft forever
    inet6 fe80::6233:4bff:fe8e:60d0/64 scope link
       valid_lft forever preferred_lft forever
3: wifi0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 60:33:4b:09:d2:da brd ff:ff:ff:ff:ff:ff

#+BEGIN_SRC sh
  su
  ip link set neteth0 up
#+END_SRC

#+RESULTS:
** openDNS.  Changing your DNS server:
   To use alternative DNS servers, edit /etc/resolv.conf and add them to the top of the file so they are used first,
   optionally removing or commenting out already listed servers.
   https://wiki.archlinux.org/index.php/Resolv.conf#Preserve_DNS_settings
