#+TITLE: Core Utilities Cheat Sheet
#+AUTHOR: Joshua Branson


* Common Options
** source of randon data
/dev/random and /dev/urandom can be used as the random number generator
--random-source=FILE

** Traversing Symbolic links
chown, chgrp, and chmod all accept -R  or the recursive option, which means do this command for all directories
underneath what this command specifies

#+BEGIN_SRC sh
ls ~/Documents/
#+END_SRC

#+RESULTS:


#+BEGIN_SRC sh
chown joshua ~/documents/
#+END_SRC

* find
  - find and report all php files in the specified dir current directory
    #+BEGIN_SRC sh :dir ~/programming/waypoint/nutripledge/
    find . -name '.*php' -print
    #+END_SRC

    #+RESULTS:
    | ./calendar1/__MACOSX/supercali-1.0.8/._modules.php                    |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._week.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._year.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._upcoming.php           |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._grid.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._weeklist.php           |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._day_week_functions.php |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._quarter.php            |
    | ./calendar1/__MACOSX/supercali-1.0.8/modules/._day.php                |
    | ./calendar1/__MACOSX/supercali-1.0.8/._edit_users.php                 |
    | ./calendar1/__MACOSX/supercali-1.0.8/._delete_event.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/._admin_actions.php              |
    | ./calendar1/__MACOSX/supercali-1.0.8/._edit_links.php                 |
    | ./calendar1/__MACOSX/supercali-1.0.8/._bad_password.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/._login.php                      |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._notify.php            |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._session_start.php     |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._nav.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._start.php             |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._footer.php            |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._top_nav.php           |
    | ./calendar1/__MACOSX/supercali-1.0.8/includes/._hidden_fields.php     |
    | ./calendar1/__MACOSX/supercali-1.0.8/._edit_categories.php            |
    | ./calendar1/__MACOSX/supercali-1.0.8/._upload_events.php              |
    | ./calendar1/__MACOSX/supercali-1.0.8/._edit_groups.php                |
    | ./calendar1/__MACOSX/supercali-1.0.8/._edit_event.php                 |
    | ./calendar1/__MACOSX/supercali-1.0.8/._user_profile.php               |
    | ./calendar1/__MACOSX/supercali-1.0.8/lang/._en_us.php                 |

    To find all of the specified files in all of the subdirectories starting with dir
    #+BEGIN_SRC sh :dir ~/programming/waypoint/henriott-group/
    find . -name \*.php -print
    #+END_SRC

    #+RESULTS:
    | ./.#b3.php                    |
    | ./history.php                 |
    | ./staff.php                   |
    | ./p7.php                      |
    | ./about.php                   |
    | ./p5.php                      |
    | ./talk.php                    |
    | ./b3.php                      |
    | ./industries.php              |
    | ./account.php                 |
    | ./industry-pictures.php       |
    | ./2.php                       |
    | ./css/connect-to-database.php |
    | ./contact.php                 |
    | ./b4.php                      |
    | ./includes/footer.php         |
    | ./includes/nav.php            |
    | ./includes/header.php         |
    | ./products.php                |

    To find all of the selected files (including sub-directories) and then delete them

  #+BEGIN_SRC sh :dir ~/programming/waypoint/nutripledge/
   find . -name \*.pdf -exec /bin/rm {} \;
   #+END_SRC

  #+RESULTS:

* grep
  #+BEGIN_SRC
  grep OPTIONS PATTERN INPUT_FILE_NAMES
  #+END_SRC

  If you want to search for a regexp in the current directory and all sub-directories

  #+BEGIN_SRC
  grep -lr "<PATTERN>"
  #+END_SRC

* permissions
In Unix everything is a file.  When you write a text document called "text.text", that is a Unix file.  When you create a directory (Windows users call this a folder) called "Music",  you also are creating a Unix file.  Obviously, "text.text" and "Music" behave very differently.  One has your favorite songs, and the other is a text document, BUT the linux kernel assumes that they are both Unix files.  All unix files have read, write, and execute permissions specific to each unix file.  This typiccally means that the ordinary user joshua cannot read, write, or execute anything in the =/root/= folder.

# I found this segment online here: https://stackoverflow.com/questions/6732430/how-do-i-give-write-permission-to-file-in-linux
#+BEGIN_SRC latex
read     = 4
write    = 2
execute  = 1
owner    = read | write = 6
group    = read         = 4
other    = read         = 4
The basic syntax of the command to set the mode is

chmod 644 [file name]
In C, that would be

#include <sys/stat.h>

chmod("[file name]", 0644);
 #+END_SRC

#+RESULTS:
#+BEGIN_LaTeX
read     = 4
write    = 2
execute  = 1
owner    = read | write = 6
group    = read         = 4
other    = read         = 4
The basic syntax of the command to set the mode is

chmod 644 [file name]
In C, that would be

#include <sys/stat.h>

chmod("[file name]", 0644);
#+END_LaTeX

** chmod

chmod [-R ] <owner> [file | directory]

Change a file's modifications.  This specifies if what user, group, and if everyone else can read, write, or execute the file.

Permissions can modify the permissions of the user's, the group's and all others.

** chown

chown [-R] <owner> [file | directory]

Change the file's owner.  The file's owner is typically root or an ordinary user.

Examples include


** chgrp

chgrp [ -R ] <group> [file | directory]

Change the group that the file or directory belongs to.

* basic usage of the find command in GNU
  #+BEGIN_SRC sh
    find . -name "pattern" -print

    find . -name "this-file.*" -print

    find . -name "this-file.*txt" -print

    find . -name "this-file\.txt" -print
  #+END_SRC
* touch -amc filename updates the files timestamps
  Access
  Modify
  Change
* show available disk space
* sort

sort [OPTION] [FILE]
** options
*** -f ignore case
*** -g general numeric sort
*** -h human numeric sort
This is good for sorting

50M
-10G
1.5K
*** -M month sort
*** -n numeric sort
*** -r reverse sort
*** -R random sort
*** -t SEPARATOR
use SEPARATOR as the field separator.  By default that separator is a space.  ([[info:coreutils#sort%20invocation][info:coreutils#sort invocation]])
* How I got my local apache server working again:

 For some reason, my ~/ folder had permissions =drwxrws---=

 To fix it I did

 #+BEGIN_SRC bash :exports both
 cd /home/; chmod g-s joshua; ls -lh | grep joshua

 #+END_SRC

 #+RESULTS:
 : drwxrwx--- 83 joshua http 4.0K Feb  2 08:04 joshua

The s was magically replaced with a x
* common things that you might want to do
** get a list of files with specific attributes and have grep search those files lines matching a regexp

  find . -name "*org" | grep -r "[pP]rettyhorses"
