#+TITLE:Emacs Cheatsheat
#+AUTHOR:Joshua Branson
#+OPTIONS: H:10 toc:nil

* dired commands
  - ~n~ next line
  - ~p~ previous line
  - ~m~ make the current file under point
  - ~u~ unmark the current file under point
  - ~* /~ mark all directories
  - ~* *~ mark all executables
  - ~* s~ mark all files in the current sub-directory
  - ~% m REGEXP <RET>  mark files based on a regular expression
  - ~Q~ dired-do-query-replace-regexp lets you search and replace all marked files
    -  Press y, to replace the current match
    -  press ~n~ to not skip the current match
    -  press ~!~ to replace all the matches in the current buffer
    -  Press ~Y~ to replace all the remaining matches without question
  - how to recursively search and replace

    M-x find-name-dired: you will be prompted for a root directory and a filename pattern, but this file name pattern uses find’s
    version of grep.  So it does not understand “.*“.  Instead “*” is equivalent to “.*”
    Press t to "toggle mark" for all files found.
    Press Q for "Query-Replace in Files...": you will be prompted for query/substitution regexps.
    Proceed as with query-replace-regexp: SPACE to replace and move to next match, n to skip a match, etc.
      -  Press y, to replace the current match
      -  press ~n~ to not skip the current match
      -  press ~!~ to replace all the matches in the current buffer
      -  Press ~Y~ to replace all the remaining matches without question

* Built in Emacs Features
** Registers
  Number Registers

  -`C-u number C-x r n r`
  Store number into register r (number-to-register).

  `C-u number C-x r + r`
  If r contains a number, increment the number in that register by number. Note that command C-x r + (increment-register) behaves differently if r contains text. See Text Registers.

  `C-x r i r`
  Insert the number from register r into the buffer.

  `C-x r i` is the same command used to insert any other sort of register contents into the buffer. `C-x r +` with no numeric argument increments the register value by 1; `C-x r n` with no numeric argument stores zero in the register.

  =C-x r s R=  save text to register R
  =M-x append-to-register R= appends text to Register R
** Macros
  - `@ <letter>` perform keyboard macro
  - `C-x Q`  prompt the user for input
  - =C-x q= prompt, when you use this macro if you want to continue.  You can enter C-r to briefly step out of the macro
    and do some edits yourself, then C-M-c will allow you to continue execution of the macro

*** My personal keybindings
  - `C-c r <letter>` begin recording keyboard macro
  - `C-c r <letter>` end recording keyboard macro
** Bookmarks
  Emacs bookmarks are nifty ways of saving your place in a file.

  - =C-x r m=  sets a bookmark for you at point and it prompts you to name it
  - =C-x r b=  jumps you to a bookmark
** windows commands
  In emacs the entire emacs program takes up a *frame*.  But emacs allows you to view two different files in the same frame, by
  splitting the frame in half, or in two *windows*.

  - =C-x o= Delete the selected window
  - =C-x 1= Delete all the windows except the one that currently has point
  - =C-x ^= make the selected window taller
  - =C-x {= make the selected window narrower
  - =C-x }= make the selected window wider
  - =C-x -= shrink this window if it doesn't need that many lines.
  - =C-x += make all the windows the same height
** Selective Display
  Emacs can display portions of the buffer based on level of indentention.  This lets you get a nice overview of the file, which
  is quite cool.
  - =C-u n C-x $= hides rows that are indented n times
  - =C-x $=  shows all rows
** Rectangles
  You can easily create a rectangle with evil mode with C-v.  Once you have a rectangle you can do these commands:

  =C-x r o= insert blank spaces to the left of the rectangle region
  =C-x r N= insert numbers all along the left of the rectangle region
** narrowing
  are entered via this syntax
  ~C-x n <letter>~

  ~d~ narrow to defun
  ~r~ widen to region
  ~s~ narrow to a org subtree
  ~w~ widden to the whole buffer
* Emacs modes
** bug-hunter
   This will help you find bugs in your init file. SOOO helpful.
  https://github.com/Malabarba/elisp-bug-hunter
  M-x bug-hunter-init-file
** helm mode
  HOLY BLIMEY COW!!! THIS MODE IS AWESOME enable it!

  C-c C-f helm-find-files

  In this mode typing "~/ manage js$"
  will display a list of files in my home directory that contain the work 'manage' and end is js

  Typing C-l will display the files is the parent directory
  Typing C-z when point is on a directory, will show the files in that directory

  Helm has nth commands. Instead of typing tab to get to the action menu
  just press C-e for the 2nd action
  and C-j for the 3rd action.
  You can also bind a key to an action menu
  (define-key helm-map (kbd "<C-tab>") 'helm-select-4th-action)

  C-c C-u lets you view an image

  Apparently helm lets you open files externally in helm-find-files with C-c C-x (not working though)

  I can make personal actions on to run on files via eshell WOW!!!!

  C-SPC will mark files that you can perform actions on

  You can then hit copy files in the action menu, which will let you select a new destionation to copy the files. so cool!
  You can do the same thing from the action menu with rename, symlink, hardlink

  helm has support for etags
  C-h e  will search the tags file
  the above should create the TAGS file with tags, but it's not working
  find . -iregex .*\.el$ | xargs etags

  check out pcomplete extension
  https://github.com/thierryvolpiatto/pcomplete-extension

*** commands
  I can also write my own helm commands cool!
  =C-c h m=  open helm-man-woman
  =C-c h h g= open helm info gnus
  =C-c h h r= open the helm-emacs-info
  =C-c h b= is helm-resume which opens up the last instance that you were on
** evil mode
  " <letter> yy   stores the whole line into register <letter>
  " <letter> p    puts the whole line back
  =vip= select the paragraph that point is in.

  check out filters. It lets you take a line, and throw that line as a command.
  It lets you create macros that you can take a line as a command to line in bash.
  interesting
*** filters VERY cool. put the contents of the buffer through a shell command!

   You can take a line like

   hello how are you   :.!wc -w   -->   4
   hello how are you   :.!wc -c   -->   21

   5 / 6  :.!bc -l   -->  .83333333333333333333

 5    :105,109!sort --> 1
 4                    2
 3                    3
 2                    4
 1                    5

 Sort has lots of options.  I can do sort -r by reverse order, sort -k4  the 4th column, sort -n sort numerically


 hello how are you
 hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you

 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you
 hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you

 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you
 hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you
 hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you

 hello how are you
 hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
 hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you hello how are you
** El-doc
  Set up el-doc for various modes. It shows help documentation as you write a function cool!
** Semantic

   Most emacs modes use a bunch of regular expressions to highlight source code. BUT semantic tries to make this better by
   parsing the code and creating grammar with it.
*** User commands
    - =C-c , j= prompt for a tag in the currect file and move point to it.
    - =C-c , J= prompt for a tag in any file that emacs has parsed and move point to it.
** ttd-mode let's you specify a compile command. Everytime you save a file, it will run your compile command.
  If it finds an error, it will alert you at the bottom!
** Undo tree
learn more about undo tree
** Paredit mode
   Paredit mode is a superior way to interact with lisps.  It essentially offers 2 features: slurping and barfing.
   - slurping elongates the current sexp by pulling in the closest sexp (either forward or backward)
   - barfing shortens the currect sexp by pushing out the closest sexp (either forward or backward)

     #+BEGIN_SRC emacs-lisp
       (hello yes (how are you point) there it is) ;; C-c ) or M-x paredit-forward-slurp-sexp was used here
       (hello yes (how are you point there) it is)
       (hello yes (how are you) point there it is) ;; C-c } or M-x paredit-forward-barf-sexp was used here

       (yup howdie (point is cool) it sure is)  ;; C-c ( or M-x paredit-backward-slup sexp was used here
       (yup (howdie point is cool) it sure is)
       (yup howdie (point is cool) it sure is)  ;; C-c { or M-x paredit-backward-barf-sexp was used here

       ;; from here on is me playing with paredit

       (defun simple-function ()
         (interactive)
         "Hello there you silly people"
         (do something)
         (do (something else))
         (do (some more (things)))
         (cond
          ((string-match "/php/+$" buffer-file-name)
           (do (some things)))

          ((string-match "/js/+$" buffer-file-name)
           (do (some things)))))
     #+END_SRC

** Restclient mode
  install restclient. It lets you query the server via get and post.  I can view the results via emacs!
** sunrise-commander is a dired derived mode that acts like filezilla inside emacs.
   =C= copy the current file into the other directory
   =C-u C= copy the current file/files into the other directory in a background process
** ediff
   Ediff is emacs's cool way of camparing two files.  It's very cool.
*** Commands
   - =a= copies buffer a diff to buffer b
   - =b= copies buffer b diff to buffer a
   - =A= toggles readonly mode of buffer a
   - =B= toggles readonly mode of buffer b
   - =wa= save buffer a
   - =wb= save buffer b
   - =!= update the differance regions.  If you press =a= and =b= multiple times, you should probably do a =!=
   - =*= highlights the words in the diff region that differ
   - =ra= restore the diff region in buffer a
   - =rb= restore the diff region in buffer b
   - =z= suspend the ediff session
   - =s= make the merge buffer as small as possible

   When you specify files, you can edit the files as root using tramp's syntax like this.

   /su::/path/to/file
** tramp is an emacs extension that lets you edit remote files
  it's syntax is done by pressing C-x C-f (find-file) then typing one of the following:

     /HOST:FILENAME
     /USER@HOST:FILENAME
     /USER@HOST#PORT:FILENAME
     /METHOD:USER@HOST:FILENAME
     /METHOD:USER@HOST#PORT:FILENAME
* Regexp
  Regular expressions are nifty ways of specify region of text.  Even coolier, they act as smart ways to replace text.

  Consider this example

  #+BEGIN_SRC php
    if (isadmin() || ismanager ()) {
        //some code here
    }
  #+END_SRC

  Suppose that you want to add a space between both "is" in the functions.

  M-x dired-do-query-replace-regexp is\(admin\|manager\) RET is \1 RET
* Elisp macro Defadvice
  learn about defadvice run commands after or before you execute some command. very cool!
  This is the old way of doing it. The newer was is to say add-function
  (defadvice kill-line (after say-ouch activate)
  (message "Ouch!"))
* there is a php package that turns all php functions into yasnippets.  It lets you easily type out a php function
  tab, and it will complete it for you. I'll need to check it out. What's it called?
* in dired mode bind a command to wdired-change-to-wdired-mode.  It lets you edit the contents of the dired!
