#+TITLE:Emacs Cheatsheat
#+OPTIONS: H:10

* Basic Concepts
** Layers
   You can stack transparent layers on top of one another in gimp to create one complete image that is looked at from above all layers.
   This lets you change one layer without affecting any other layer
*** layers dialog
    Click on Windows > dockable dialogs > Layers or C-l
    Each layer has a eye. If you see the eye, the layer is visible. Click on it, the eye will disappear and the layer will be invisible.
    Each layer has a chain. If you see a chain, on several layers, then you can do operations on all of those layers. ie:
    You can have the chain visible on 2 layers but not the 3rd layer. When you select a part of the image to cut, you cut the 1st and
    2nd layer, BUT not the 3rd.
** Channels
   There are basically 3 channels.  Blue, red, and green.  The blue channel, is what the image looks like when all you see is blue.
   This is nice, because you can easily delete or change just the blue on the image without affecting the image's red or green parts.
** To see the colors in GIMP press `O` for color picker, then open the pointer window

Window > Dockable Dialogues > Pointer

The color codes are listed there.
** To enter single window mode Windows > Single-Window-Mode
** To show the tools menu > C-b
** to delete a selection (ie: make that selection have no colors, and you'll see the grey and black of the layer)
  select the area, via recangle, elipse, or magic wand, then press edit > clear
** to copy part of an image
  select the part that you want to copy, right click on it, edit > copy
  In the top of the menu bar edit > paste as new image or now layer
** You can merge layers by right clicking on any layer and clicking merge visible layers
 Entered on [2015-08-16 Sun 18:29]

   [[file:~/manuals/gimp.org]]
** You can expand the layer boundary by right clicking on the layer and clicking on layer boundary size or clicking on layer to image size
 Entered on [2015-08-16 Sun 18:29]

   [[file:~/manuals/gimp.org]]
