* Intro to PHP
Mike Atwell
** Functions
 - Date
 - Directory
 - Filesystem
 - filter
 - string
 - calendar
 - array
** I can embed php inside an html file,
 BUT perhaps I should not do this.  I should use a template system.
** You can use PHP other than web developments
* Otto

All products except for atlas are open source.  hashicorp

Otto is the successor to Vagrant. Most of their stuff is written in Go.  It is an alternative to docker.  It is a wrapper around virtual box.  It's how mozilla's MDN is written.  So it is libre.

otto ssh can be set up in milliseconds. It's configurable.

 =otto infra=  will analyze my application and will give me some tips about how to assign network stuff

 =otto status=

** setting up an example application
 - =otto compile=

 - =otto dev=

 - =otto dev ssh=
 puts you in the node js app inside the virtual maching

 - =npm install=

 - =otto status=

 - =otto infra=
* Git a job
 An intro to version control.  They used to be centralized.  There is only one repo in this.  There is a lock on a file when someone checks it out.  Git and mercurial are distributed version controls and they rock!
** Vocab
- diff or delta  represent the changes in a file
- fork  this is two copies of projects.  But the original and the fork can go in completely different directions.
  My fork of melpa is a fork of the original melpa
- checkout    What is this?
- push    I push my code to my personal forked repo
- pull request.  I make a pull request that my changes get added into stuff.

  Try github is a basic intro

  git for teams resources  is another good resource
* open data ironhacks at Purdue

There is a LOT of open data out there.  I could make some seriously awesome programs that utilizes this open data.

3 high energy weeks of hacking

everyone can use anyone else' code during the hackathon

I can participate at Purdue's Iron hacks

** iron hacks last year used open data helped them find nice neighborhood to live in
