\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename gawk.info
@settitle Gawk Cheatsheat
@c %**end of header
@copying
Basics of Gawk.

Copyright @copyright{} 2014

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.

A copy of the license is also available from the Free Software
Foundation Web site at @url{http://www.gnu.org/licenses/fdl.html}.

@end quotation

The document was typeset with
@uref{http://www.texinfo.org/, GNU Texinfo}.

@end copying

@titlepage
@title Gawk Cheatsheat
@subtitle Basics of Gawk
@author  <joshua@arch>
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top, Basics, (dir), (dir)
@top Gawk Cheatsheat

@insertcopying
@end ifnottex

@c Generate the nodes for this menu with `C-c C-u C-m'.
@menu
@end menu

@c Update all node entries with `C-c C-u C-n'.
@c Insert new nodes with `C-c C-c n'.
@node Basics
@chapter Basics

Gawk is a program that processes data super super well!!!! It is
really great for looking in a text file and finding say the 3rd and
5th words on every line or specified lines.

There are several ways to call gawk

gawk '/pattern/{action}' <data_file>

<some command> | gawk '/pattern/{action}'

gawk -f <gawk_program> <data_file>

$1 $2 $3 tell gawk to print the 1st, 2nd, and 3rd, word in a database
file. The default word seperator is a space or " ", but this can be
modified by changing one a gawk's variables.

Here is a cool example:

amixer get Master | grep '[0-9]%' | gawk '{ print $4 }'

@node Copying This Manual
@appendix Copying This Manual

@menu
* GNU Free Documentation License::  License for copying this manual.
@end menu

@c Get fdl.texi from http://www.gnu.org/licenses/fdl.html
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye

@c gawk.texi ends here
