\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename keyboard_shortcuts.info
@settitle Keyboard Shortcuts
@c %**end of header
@copying
This is a collection of awesome keyboard shortcuts..

Copyright @copyright{} 2014

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.

A copy of the license is also available from the Free Software
Foundation Web site at @url{http://www.gnu.org/licenses/fdl.html}.

@end quotation

The document was typeset with
@uref{http://www.texinfo.org/, GNU Texinfo}.

@end copying

@titlepage
@title Keyboard Shortcuts
@subtitle This is a collection of awesome keyboard shortcuts.
@author  <joshua@arch>
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top Keyboard Shortcuts

@insertcopying
@end ifnottex

@c Generate the nodes for this menu with `C-c C-u C-m'.
@menu
@end menu

@c Update all node entries with `C-c C-u C-n'.
@c Insert new nodes with `C-c C-c n'.
@node Linux Kernel Shortcuts
@chapter Linux Kernel Shortcuts

@table
@item M-Alt-r
@emph{Unraw} take control of the keyboard back from X
@item M-Alt-e
@emph{Terminate} Send SIGTERM to all processes, which allows them to terminate gracefully
@item M-Alt-i
@emph{Kill} send SIGKILL to all processes, which forces them to terminate NOW!
@item M-Alt-s
@emph{Sync} flush data to disk
@item M-Alt-u
@emph{Unmount} unmount and remount all filesystems read only
@item M-Alt-b
@emph{Reboot} reboot
@end table

@node Virtual console
@chapter Virtual console

@table
@item Ctrl+Alt+Del
Reboots Computer (specified by the symlink /usr/lib/systemd/system/ctrl-alt-del.target)
@item Alt+Fn+F1, F2, F3, ...
Switch to n-th virtual console
@item Alt+ ←
Switch to previous virtual console
@item Alt+ →
Switch to next virtual console
@item Scroll Lock
When Scroll Lock is activated, input/output is locked
@item Shift+PgUp/PgDown
Scrolls console buffer up/down
@item Ctrl+c
Kills current task
@item Ctrl+d
Inserts an EOF
@item Ctrl+z
Pauses current Task
@end table

@node Copying This Manual
@appendix Copying This Manual

@menu
* GNU Free Documentation License::  License for copying this manual.
@end menu

@c Get fdl.texi from http://www.gnu.org/licenses/fdl.html
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye

@c keyboard_shortcuts.texi ends here
