;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	end-of-buffer
	end-of-visual-line
	eval-last-sexp
	evil-append
	evil-delete
	evil-emacs-state
	evil-forward-char
	evil-normal-state
	evil-previous-line
	helm-confirm-and-exit-minibuffer
	org-self-insert-command
	sgml-slash
	viper-beginning-of-line
	viper-change-state-to-vi
	viper-command-argument
	viper-del-backward-char-in-insert
	viper-insert
	viper-repeat
	viper-replace-char
	viper-toggle-key-action
	viper-undo
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-exit-emacs-state
	evil-next-line
	evil-yank
	viper-backward-char
	viper-digit-argument
	viper-intercept-ESC-key
	))
